# Generated by Django 4.2.11 on 2024-04-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguontruyen',
            name='element',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nguontruyen',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='nguontruyen',
            name='nextElement',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nguontruyen',
            name='previousElement',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
