# Generated by Django 4.2.11 on 2024-04-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_nguontruyen_element_alter_nguontruyen_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguontruyen',
            name='element',
            field=models.CharField(blank=True, default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nguontruyen',
            name='link',
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nguontruyen',
            name='nextElement',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='nguontruyen',
            name='previousElement',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
