# Generated by Django 4.2.11 on 2024-05-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_nguontruyen_element_alter_nguontruyen_link_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nguonTruyen',
        ),
    ]
