# Generated by Django 4.2.11 on 2024-04-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='texttospeech',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='texttospeech',
            name='code',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
