# Generated by Django 4.2.11 on 2024-04-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts_api', '0002_alter_texttospeech_options_texttospeech_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texttospeech',
            name='code',
            field=models.TextField(default='default code'),
        ),
        migrations.AlterField(
            model_name='texttospeech',
            name='text',
            field=models.TextField(default='default text'),
        ),
        migrations.AlterField(
            model_name='texttospeech',
            name='url',
            field=models.URLField(default='https://example.com'),
        ),
    ]
