# Generated by Django 4.2.11 on 2024-04-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts_api', '0003_alter_texttospeech_code_alter_texttospeech_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='texttospeech',
            options={},
        ),
        migrations.RemoveField(
            model_name='texttospeech',
            name='code',
        ),
        migrations.RemoveField(
            model_name='texttospeech',
            name='text',
        ),
        migrations.AddField(
            model_name='texttospeech',
            name='element',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='texttospeech',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='texttospeech',
            name='url',
            field=models.URLField(),
        ),
    ]
