# Generated by Django 4.2.11 on 2024-05-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tts_api', '0004_alter_texttospeech_options_remove_texttospeech_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextToSpeech',
        ),
    ]
